<?xml version="1.0"?><?codewarrior exportversion="1.0" ideversion="4.0"?><!DOCTYPE PROJECT [<!ELEMENT PROJECT (TARGETLIST, TARGETORDER, GROUPLIST, DESIGNLIST?)><!ELEMENT TARGETLIST (TARGET+)><!ELEMENT TARGET (NAME, SETTINGLIST, FILELIST?, LINKORDER?, SEGMENTLIST?, OVERLAYGROUPLIST?, SUBTARGETLIST?, SUBPROJECTLIST?)><!ELEMENT NAME (#PCDATA)><!ELEMENT USERSOURCETREETYPE (#PCDATA)><!ELEMENT PATH (#PCDATA)><!ELEMENT FILELIST (FILE*)><!ELEMENT FILE (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?, ROOTFILEREF?, FILEKIND?, FILEFLAGS?)><!ELEMENT PATHTYPE (#PCDATA)><!ELEMENT PATHROOT (#PCDATA)><!ELEMENT ACCESSPATH (#PCDATA)><!ELEMENT PATHFORMAT (#PCDATA)><!ELEMENT ROOTFILEREF (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)><!ELEMENT FILEKIND (#PCDATA)><!ELEMENT FILEFLAGS (#PCDATA)><!ELEMENT FILEREF (TARGETNAME?, PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)><!ELEMENT TARGETNAME (#PCDATA)><!ELEMENT SETTINGLIST ((SETTING|PANELDATA)+)><!ELEMENT SETTING (NAME?, (VALUE|(SETTING+)))><!ELEMENT PANELDATA (NAME, VALUE)><!ELEMENT VALUE (#PCDATA)><!ELEMENT LINKORDER (FILEREF*)><!ELEMENT SEGMENTLIST (SEGMENT+)><!ELEMENT SEGMENT (NAME, ATTRIBUTES?, FILEREF*)><!ELEMENT ATTRIBUTES (#PCDATA)><!ELEMENT OVERLAYGROUPLIST (OVERLAYGROUP+)><!ELEMENT OVERLAYGROUP (NAME, BASEADDRESS, OVERLAY*)><!ELEMENT BASEADDRESS (#PCDATA)><!ELEMENT OVERLAY (NAME, FILEREF*)><!ELEMENT SUBTARGETLIST (SUBTARGET+)><!ELEMENT SUBTARGET (TARGETNAME, ATTRIBUTES?)><!ELEMENT SUBPROJECTLIST (SUBPROJECT+)><!ELEMENT SUBPROJECT (FILEREF, SUBPROJECTTARGETLIST)><!ELEMENT SUBPROJECTTARGETLIST (SUBPROJECTTARGET*)><!ELEMENT SUBPROJECTTARGET (TARGETNAME, ATTRIBUTES?)><!ELEMENT TARGETORDER (ORDEREDTARGET|ORDEREDDESIGN)*><!ELEMENT ORDEREDTARGET (NAME)><!ELEMENT ORDEREDDESIGN (NAME, ORDEREDTARGET+)><!ELEMENT GROUPLIST (GROUP|FILEREF)*><!ELEMENT GROUP (NAME, (GROUP|FILEREF)*)><!ELEMENT DESIGNLIST (DESIGN+)><!ELEMENT DESIGN (NAME, DESIGNDATA)><!ELEMENT DESIGNDATA (#PCDATA)>]><PROJECT>    <TARGETLIST>        <TARGET>            <NAME>68K Static Library</NAME>            <SETTINGLIST>                <!-- Settings for "Source Trees" panel -->                <SETTING><NAME>UserSourceTrees</NAME><VALUE></VALUE></SETTING>                <!-- Settings for "Custom Keywords" panel -->                <SETTING><NAME>CustomColor1</NAME>                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>                </SETTING>                <SETTING><NAME>CustomColor2</NAME>                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>                </SETTING>                <SETTING><NAME>CustomColor3</NAME>                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>                </SETTING>                <SETTING><NAME>CustomColor4</NAME>                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>                </SETTING>                <!-- Settings for "Access Paths" panel -->                <SETTING><NAME>AlwaysSearchUserPaths</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>InterpretDOSAndUnixPaths</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>UserSearchPaths</NAME>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>::</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                </SETTING>                <SETTING><NAME>SystemSearchPaths</NAME>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:MSL:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:MacOS Support:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                </SETTING>                <!-- Settings for "Target Settings" panel -->                <SETTING><NAME>Linker</NAME><VALUE>MacOS 68K Linker</VALUE></SETTING>                <SETTING><NAME>PreLinker</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>PostLinker</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>Targetname</NAME><VALUE>68K Static Library</VALUE></SETTING>                <SETTING><NAME>OutputDirectory</NAME>                    <SETTING><NAME>Path</NAME><VALUE>:</VALUE></SETTING>                    <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                    <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                </SETTING>                <SETTING><NAME>SaveEntriesUsingRelativePaths</NAME><VALUE>false</VALUE></SETTING>                <!-- Settings for "File Mappings" panel -->                <SETTING><NAME>FileMappings</NAME>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>APPL</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>Appl</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>MMLB</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Lib Import 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>MPLF</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Lib Import 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>MWCD</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>OBJ </VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MPW Import 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>RSRC</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.bh</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Balloon Help</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.c</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.c++</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.cc</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.cp</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.cpp</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.exp</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.h</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.p</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW Pascal 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.pas</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW Pascal 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.pch</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.pch++</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.ppu</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW Pascal 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.r</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Rez</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.seg</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>docu</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>rsrc</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>shlb</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>PEF Import 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>stub</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>PEF Import 68K</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.doc</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>                    </SETTING>                </SETTING>                <!-- Settings for "Build Extras" panel -->                <SETTING><NAME>CacheModDates</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>ActivateBrowser</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>DumpBrowserInfo</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>CacheSubprojects</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>UseThirdPartyDebugger</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>DebuggerCommandLine</NAME><VALUE></VALUE></SETTING>                <PANELDATA><NAME>Debugger Runtime</NAME><VALUE>                    0002000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    00000000000000000000000000000000                </VALUE></PANELDATA>                <!-- Settings for "Debugger Target" panel -->                <SETTING><NAME>LogSystemMessages</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>AutoTargetDLLs</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>StopAtWatchpoints</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>PauseWhileRunning</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>PauseInterval</NAME><VALUE>5</VALUE></SETTING>                <SETTING><NAME>PauseUIFlags</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>AltExePath</NAME>                    <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>                    <SETTING><NAME>PathFormat</NAME><VALUE>Generic</VALUE></SETTING>                    <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                </SETTING>                <SETTING><NAME>StopAtTempBPOnLaunch</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>CacheSymbolics</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>TempBPFunctionName</NAME><VALUE>main</VALUE></SETTING>                <SETTING><NAME>TempBPType</NAME><VALUE>false</VALUE></SETTING>                <!-- Settings for "